// cspell:disable

/**
 * Generated by https://quicktype.io
 */
// prettier-ignore
export type VehicleProduct = {
  // class:         string;
  class:         "C4" | "C3" | "C2" | "C1" |
                 "B4" | "B3" | "A7" | "A6" |
                 "A5" | "A4" | "A3" | "A2" | "A1";
  // brand:         string;
  brand:         "Alfa Romeo" | "Ariel" | "Ascari" | "Aston Martin " | "Audi" |
                 "Bugatti" | "Caterham" | "Chevrolet" | "Chrysler" | "Dodge" |
                 "Ferrari" | "Ford" | "Gumpert" | "Hummer" | "Jaguar" | "Jeep" |
                 "Koenigsegg" | "Lamborghini" | "Lancia" | "Land Rover" | "Lotus" |
                 "McLaren" | "Mercedes-Benz" | "Nissan" | "Pagani" | "RUF" |
                 "Saleen" | "Subaru" | "TVR" | "Toyota" | "Volkswagen";
  model:         string;
  acceleration:  number;
  topSpeed:      number;
  braking:       number;
  price:         number;
  // configuration: string;
  configuration: "AWD" | "FWD" | "RWD";
  // capacity:      number;
  capacity:      1 | 2 | 4;
  // body:          string;
  body:          "Coupe" | "Hatchback" | "Muscle" | "Roadster" | "SUV" | "Sedan" | "Supercar" | "Tourer" | "Track" | "Wagon";
  description:   string;
  image:         string;
  imagePath:     string;
}

/**
 * Must add data here...
 */
const data: VehicleProduct[] = [];
export default data;
