// prettier-ignore
/** Generated by https://quicktype.io */
export type Vehicle = {
  id:            string;
  class:         string;
  brand:         string;
  model:         string;
  acceleration:  number;
  topSpeed:      number;
  braking:       number;
  price:         number;
  configuration: string;
  capacity:      number;
  body:          string;
  description:   string;
  image:         string;
  imageSrc:      string;
}

export type VehicleID = Vehicle["id"];
